# Generated by Django 6.0.3 on 2026-04-03 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Cuota')),
                ('amount', models.IntegerField(verbose_name='Monto por alumno')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PagoCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False, verbose_name='Pagado')),
                ('paid_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='fondos.cuota', verbose_name='Cuota')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='fondos.student', verbose_name='Alumno')),
            ],
            options={
                'verbose_name': 'Pago de Cuota',
                'verbose_name_plural': 'Pagos de Cuotas',
                'unique_together': {('student', 'cuota')},
            },
        ),
    ]
