# Generated by Django 6.0.3 on 2026-04-10 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0002_cuota_pagocuota'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Curso')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-year', 'name'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='fondos.curso', verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='cuota',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuotas', to='fondos.curso', verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='student',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='fondos.curso', verbose_name='Curso'),
        ),
        migrations.CreateModel(
            name='CursoMembresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('TESORERO', 'Tesorero'), ('AYUDANTE', 'Ayudante'), ('APODERADO', 'Apoderado')], max_length=20, verbose_name='Rol')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='fondos.curso', verbose_name='Curso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Membresía de Curso',
                'verbose_name_plural': 'Membresías de Curso',
                'unique_together': {('user', 'curso')},
            },
        ),
    ]
