# Generated by Django 6.0.3 on 2026-04-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0003_curso_activity_curso_cuota_curso_student_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursomembresia',
            name='is_principal',
            field=models.BooleanField(default=False, verbose_name='Tesorero Principal'),
        ),
    ]
