# Generated by Django 6.0.3 on 2026-04-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0004_cursomembresia_is_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='tipo',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('AVANZADO', 'Avanzado')], default='NORMAL', max_length=20, verbose_name='Tipo de Plan'),
        ),
    ]
