# Generated by Django 6.0.3 on 2026-04-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0005_curso_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='avanzado_desde',
            field=models.DateField(blank=True, null=True, verbose_name='Plan Avanzado desde'),
        ),
        migrations.AddField(
            model_name='curso',
            name='avanzado_hasta',
            field=models.DateField(blank=True, null=True, verbose_name='Plan Avanzado hasta'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='tipo',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('AVANZADO', 'Avanzado')], default='NORMAL', max_length=20, verbose_name='Tipo de Plan (legacy)'),
        ),
    ]
