# Generated by Django 6.0.3 on 2026-04-17 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0006_curso_avanzado_desde_curso_avanzado_hasta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Monto del abono')),
                ('fecha', models.DateField(verbose_name='Fecha del abono')),
                ('nota', models.CharField(blank=True, max_length=200, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='fondos.pagocuota', verbose_name='Pago')),
            ],
            options={
                'verbose_name': 'Abono',
                'verbose_name_plural': 'Abonos',
                'ordering': ['fecha'],
            },
        ),
    ]
