# Generated by Django 6.0.3 on 2026-04-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0007_abono'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='meta_por_alumno',
            field=models.IntegerField(blank=True, null=True, verbose_name='Meta por alumno'),
        ),
    ]
