# Generated by Django 6.0.3 on 2026-04-23 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0008_meta_por_alumno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('monto_meta', models.IntegerField(blank=True, null=True, verbose_name='Meta ($)')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='fondos.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Objetivo',
                'verbose_name_plural': 'Objetivos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre / Descripción')),
                ('amount', models.IntegerField(verbose_name='Monto')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('nota', models.CharField(blank=True, max_length=300, verbose_name='Nota')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='fondos.curso', verbose_name='Curso')),
                ('objetivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='fondos.objetivo', verbose_name='Objetivo')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='objetivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='fondos.objetivo', verbose_name='Objetivo'),
        ),
        migrations.AddField(
            model_name='cuota',
            name='objetivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuotas', to='fondos.objetivo', verbose_name='Objetivo'),
        ),
    ]
