# Generated by Django 6.0.3 on 2026-04-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0009_objetivo_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetivo',
            name='multiplicador',
            field=models.IntegerField(default=1, verbose_name='Multiplicador'),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='monto_meta',
            field=models.IntegerField(blank=True, null=True, verbose_name='Meta por unidad ($)'),
        ),
    ]
