# Generated by Django 6.0.3 on 2026-04-24 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0010_objetivo_multiplicador'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetivoAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplicador', models.IntegerField(default=1, verbose_name='Multiplicador')),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos_meta', to='fondos.objetivo', verbose_name='Objetivo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos_meta', to='fondos.student', verbose_name='Alumno')),
            ],
            options={
                'verbose_name': 'Meta por Alumno',
                'verbose_name_plural': 'Metas por Alumno',
                'ordering': ['student__last_name', 'student__first_name'],
                'unique_together': {('objetivo', 'student')},
            },
        ),
    ]
